defaults:
  - _self_

name: train_robomimic_image
_target_: diffusion_policy.workspace.train_robomimic_image_workspace.TrainRobomimicImageWorkspace

exp_name: "default"
subsample_frames: 1
subsampling_method: uniform
horizon: &horizon 10
global_horizon: 32
global_obs: 2
global_action: 1
n_latency_steps: 0
dataset_obs_steps: *horizon
past_action_visible: False
keypoint_visible_rate: 1.0
shape_meta:
  action:
    shape:
    - 10
  obs:
    agentview_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
policy:
  _target_: diffusion_policy.policy.robomimic_image_policy.RobomimicImagePolicy
  shape_meta: ${shape_meta}
  algo_name: bc_rnn
  obs_type: image
  past_action_pred: true
  # oc.select resolver: key, default
  task_name: ${oc.select:task.task_name,square}
  dataset_type: ${oc.select:task.dataset_type,ph}
  crop_shape: [76,76]

dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: False
  pin_memory: True
  persistent_workers: False

task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    use_embed_if_present: false
    abs_action: true
    dataset_path: data/robomimic/datasets/square/mh/image_abs.hdf5
    horizon: ${global_horizon}
    n_obs_steps: ${global_obs}
    pad_after: 7
    pad_before: 64
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 10
      obs:
        embedding:
          shape:
          - 137
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    use_cache: false
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/square/mh/image_abs.hdf5
  dataset_type: mh
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: data/robomimic/datasets/square/mh/image_abs.hdf5
    fps: 10
    max_steps: 500
    n_action_steps: ${global_action}
    n_envs: 28
    n_obs_steps: ${global_obs}
    n_test: 40
    n_test_vis: 2
    n_train: 6
    n_train_vis: 2
    past_action: false
    render_obs_key: agentview_image
    shape_meta:
      action:
        shape:
        - 10
      obs:
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: square_image
  shape_meta:
    action:
      shape:
      - 10
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  task_name: square
task_name: square_image

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  # optimization
  num_epochs: 3050
  # training loop control
  # in epochs
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}